<?php

namespace BibliothequeBundle\Repository;

/**
 * CommentaireLivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireLivreRepository extends \Doctrine\ORM\EntityRepository
{

    public function CommentaireLivreId($id){

        $query = $this->getEntityManager()->createQuery("select c from BibliothequeBundle:CommentaireLivre c where c.Livre='$id'");
        return $query->getResult();

    }

}
