<?php

namespace BibliothequeBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getlivreparid($id){

        $query = $this->getEntityManager()->createQuery("select l from BibliothequeBundle:Livre l where l.id='$id'");
        return $query->getResult();
    }

    public function getlivreparlocation($id){

        $query = $this->getEntityManager()->createQuery("select l from BibliothequeBundle:Livre l JOIN BibliothequeBundle:Location m where l.id=m.Livre and m.id='$id'");
        return $query->getResult();


    }

public function getimageLivre($id){

}
    public function getLivresByTitreOrDesc($keyword)
    {
        $query = $this->getEntityManager()->createQuery("select l from BibliothequeBundle:Livre l where l.titre LIKE :titre OR l.description LIKE :desc")
            ->setParameter("titre", '%'.$keyword.'%')
            ->setParameter('desc', '%'.$keyword.'%');
        return $query->getResult();
    }
//    public function Meslocations($id){
//        $query = $this->getEntityManager()->createQuery("select l from BibliothequeBundle:Location m JOIN BibliothequeBundle:Livre l where m.Locataire='$id' AND l.id=m.livre");
//        return $query->getResult();
//
//    }
}
