bibliotheque_location:
    resource: "@BibliothequeBundle/Controller/LocationController.php"
    type:     annotation

bibliotheque_location:
    resource: "@BibliothequeBundle/Controller/LocationController.php"
    type:     annotation

bibliotheque_rating_livre:
    resource: "@BibliothequeBundle/Controller/RatingLivreController.php"
    type:     annotation

bibliotheque_location:
    resource: "@BibliothequeBundle/Controller/LocationController.php"
    type:     annotation

bibliotheque_commentaire_livre:
    resource: "@BibliothequeBundle/Controller/CommentaireLivreController.php"
    type:     annotation

bibliotheque_livre:
    resource: "@BibliothequeBundle/Controller/LivreController.php"
    type:     annotation

bibliotheque:
    resource: "@BibliothequeBundle/Resources/config/routing.yml"
    prefix:   /bibliotheque
app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
